import { createFileRoute } from "@tanstack/react-router";
import { FAQ, Hero, ImageGrid, SectionHeading, ServiceList, TestimonialGrid, VideoGrid, image } from "@/components/site";

// No head() here: the home route inherits title/description/og/twitter from
// __root.tsx, and ships no og:image so serve-time hosting can inject the
// project's social preview (explicit og:image or latest screenshot).
export const Route = createFileRoute("/")({ head:()=>({meta:[{title:"Eliteztudio — 3D Animation & Motion Design Studio"},{name:"description",content:"Cinematic 3D industrial, offshore, product and SaaS animation that turns complex ideas into clear visual stories."},{property:"og:title",content:"Eliteztudio — 3D Animation & Motion Design Studio"},{property:"og:description",content:"Complex ideas, brought to life through cinematic 3D animation and motion design."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"/"}]}), component: Index });

// IMPORTANT: Replace this placeholder. See ./README.md for routing conventions.
function Index() {
 const videos=[
  {id:"Jf3vcCwxA-E",title:"High-Quality 3D Industrial Animation Video",body:"Complex machinery, simplified through 3D. Visual storytelling designed to make industrial products easier to understand and sell."},
  {id:"zo-xF246rEI",title:"3D Motion Graphics SaaS Explainer Video",body:"Complex software, made simple. We turn dashboards, workflows, and features into clear motion graphics that help users onboard faster and help you convert more trials."},
  {id:"fKl_yIg77Bc",title:"High-Quality 3D Oil and gas Animation Presentation",body:"We turn complex oil and gas processes into clear, engaging 3D visuals. From drilling and pipelines to refineries and safety systems, this animation explains technical operations with precision and clarity. Built to help teams, clients, and investors understand your project fast."},
  {id:"gT_C7ws-yvg",title:"Photorealistic 3D Offshore Oil & Gas Equipment Animation",body:"Rigs, FPSOs, turbines, and subsea systems brought to life. We visualize complex operations and safety procedures that are too dangerous or expensive to film offshore."},
  {id:"KdRGRh2HKQg",title:"Top-notch 3D Industrial Animation Video",body:"From blueprint to job-site. We turn complex specs into clear visuals so $500k machines are easy to understand and sell. Helps dealers close deals without site visits."},
  {id:"UEKzx_biFVA",title:"SaaS Animation Video",body:"Turn complex software into simple visual stories. We create engaging explainers, product walkthroughs, and feature animations that make your product easy to understand."},
  {id:"E7iBM79Gd0k",title:"Motion Graphics SaaS Video",body:"Kinetic typography, transitions, and brand-led animation designed to make your message sharper, clearer, and harder to ignore."},
  {id:"5cn_gB2wUHE",title:"High-detail 3D animation of working mechanics, engine, and hydraulics.",body:"Photos can't show how your products works. We build 3D animations from your images and CAD files to explain hydraulics, processes, and maintenance in 60 seconds."},
  {id:"72t8yCfTLEc",title:"3D Industrial Factory Animation Video",body:"High-quality 3D animation that visualizes factory processes, machinery, and workflows. Made to explain complex operations clearly for clients, investors, and training."},
  {id:"WcglkyxMfJU",title:"SaaS Product Demo Video",body:"We turn complex software into clear, 60-seconds stories. Clean Ul animations, motion graphics + SFX + V/O that help teams understand, buy, and onboard faster."}
 ];
 const gallery=["IMG_6683-e2ZV1Uf0rFGaG3D9jfuCrGy11UdlyO.jpeg","5838939856766176969-4Hpd75f6OQbabojif7KTk6bxXBmtoL.jpg","IMG_6690-XFSOV93BURMGKAOLCZ7CzRsETVLUzt.jpeg","IMG_6521-omatf17b94MzD3hjH10iK5sIPNEoWu.jpeg","5838939856766176971-ueCUAVYmToNzpHf4k0NwxqbibelVNM.jpg","IMG_6738-TCEQHUn1NadjP35j2skdBBfYcTpvuH.jpeg"] as const;
  const services=[{title:"3D Industrial Animation",body:"We turn your images, photos, and CAD files into clear 3D animations. Show hydraulics, cutaways, x-ray, and exploded views so buyers understand them in 60 seconds"},{title:"SaaS Animation Video",body:"Turn complex software into simple visual stories. We create engaging explainers, product walkthroughs, and feature animations that make your product easy to understand."},{title:"Motion Graphics Design",body:"Kinetic typography, transitions, and brand-led animation designed to make your message sharper, clearer, and harder to ignore."},{title:"3D Offshore Animation",body:"3D animation for offshore oil & gas: rigs, FPSOs, turbines, and subsea systems. We visualize complex operations, safety, training, proposal and engineering concepts that are too dangerous or expensive to film."},{title:"SaaS Demo Video",body:"Show your product in action. We create polished demo videos that highlight key features, demonstrate workflows, and give viewers a clear understanding of how your software works."},{title:"3D Factory Animation",body:"We turn complex factory systems into powerful visual experiences, using detailed 3D animation to showcase machinery, production lines, and workflows with clarity and impact."}];
  const faq=[
   {q:"How do we start a project with Eliteztudio?",a:"It starts with an idea. Send us your brief through the contact page, and we’ll take it from there — asking the right questions, shaping the scope, and giving you a clear timeline and ballpark estimate to get things moving."},
   {q:"Can you work with our in-house creative team?",a:"Absolutely. We work as an extension of your team, fitting seamlessly into your existing workflow and sharing files in whatever formats you prefer. You’ll have clear communication, regular updates, and visibility at every milestone. No black box — just a smooth, collaborative process from brief to final frame."},
   {q:"What does a typical project timeline look like?",a:"Most SaaS videos and industrial animations take 1 to 2 weeks from kickoff to final delivery. Larger 3D productions like offshore, hydraulics, and heavy machinery may take longer depending on scope and complexity. Before we start, you’ll get a clear project schedule with key milestones so you always know what to expect."},
   {q:"Do you provide revisions?",a:"Absolutely. Every project includes structured review rounds at key stages — from the initial style frame and animation pass to the final polish. We keep feedback organized and focused, so you have control over the creative direction without getting caught in endless back-and-forth."},
   {q:"What do you need from us to begin?",a:"Keep it simple: your goals, brand guidelines, key assets, and a few examples of work you like. From there, we take care of the visual direction, storyboarding, animation, and production. You bring the vision and feedback. We turn it into the final frame."},
   {q:"How does payment work?",a:"We keep payment simple and transparent. An upfront deposit secures your project and allows production to begin, with the remaining balance paid according to the agreed schedule. All payment terms are confirmed before we start."},
   {q:"Do you sign NDAs?",a:"Absolutely. We’re happy to work under an NDA when your project or product requires confidentiality. Your ideas, assets, and project information are handled with discretion."},
   {q:"How does pricing work?",a:"Every project is different. Pricing depends on the scope, length, visual complexity, number of assets, and production requirements. Once we understand your project, we’ll provide a clear quote tailored to the work involved."}
  ];
  return <><Hero eyebrow="Eliteztudio" title={<>Complex Ides.<br/>Brought to Life.</>} body="We create cinematic 3D animation for industrial and consumer products, machinery, offshore, and SaaS — turning complex ideas into clear, striking visual stories built to explain, engage, and make an impact" imageUrl={image("IMG_7162-ozotM9VHFqQqzE63ZXLnn2VIHdppuL.jpeg")} primary={{label:"View work",href:"/work"}} secondary={{label:"Contact",href:"mailto:hello@eliteztudio.com"}}/>
 <section className="section"><SectionHeading eyebrow="Our Work" title={<>Stories, brought to life.</>} body="From industrial and product 3D animation to SaaS storytelling and motion design, we bring the full visual process under one roof."/><VideoGrid items={videos}/></section>
  <section className="section section-contrast"><SectionHeading eyebrow="REEL SELECTS" title={<>Built in frames. Remembered in motion.</>} body="A showcase of selected work across 3D industrial animation, 3D offshore animation, product visualization, SaaS storytelling, and motion design — where technical precision meets creative craft."/><div className="section-actions"><a href="/work" className="button button-primary">See the full reel</a><a href="mailto:hello@eliteztudio.com" className="text-link">Brief us on a project</a></div><ImageGrid items={gallery.map((src)=>({src:image(src),alt:"Selected Eliteztudio animation frame"}))}/></section>
  <section className="section split-feature"><div><SectionHeading eyebrow="OUR PHILOSOPHY" title={<>Motion isn't decoration.<br/>It's communication.</>} body={"We create 3D animation with a purpose — to turn complex ideas into clear stories, transform attention into interest, and make brands impossible to forget.\nBecause when every frame matters, the work does too."}/><div className="mini-grid"><div><h3>Motion with intent</h3><p>Every frame has a reason to exist. We use motion to guide attention, sharpen your message, and move your story forward — never just to fill the screen.</p></div><div><h3>Technical precision</h3><p>From clean topology and controlled simulations to stable renders and pixel-perfect compositing, we obsess over the details that make the final frame feel effortless.</p></div></div></div><img src={image("5838939856766176972-ObadrIMK6G2HfzldUo2F3CkswA8uFA.jpg")} alt="Central computer processor with a green leaf logo on a glowing green circuit board" loading="lazy"/></section>
  <section className="section"><SectionHeading eyebrow="WHAT WE DO" title="One studio. Endless possibilities." body="From 3D industrial, offshore, and product animation to SaaS storytelling and motion design, we bring the entire visual process under one roof — creating work that looks exceptional, communicates clearly, and moves your brand forward."/><ServiceList items={services}/></section>
  <section className="section section-contrast"><SectionHeading eyebrow="Client feedback" title="Stories that resonate. Results that speak. Hear from the brands and teams who trusted us to turn their ideas into cinematic visual experiences."/><TestimonialGrid items={[{quote:"Really impressed with the final animation. The excavator was modeled and presented with great attention to detail, and the whole machine looks powerful and realistic. Communication was smooth throughout, and the final result was exactly what we needed.",name:"Hugo Jolliffe",role:"Principal Director of jb equipMent ltd",image:image("7823bde6-6c42-42d1-827f-9ff86315039c-yd7kWYHqKPWDElVzYFbcvO95cWoa2D.jpg")},{quote:"Eliteztudio created the perfect demo video for Edbanz. They took our AI-powered education ecosystem and made it simple to understand in under a minute. From '10 apps chaos' to one unified platform — the animation, UI flow, and messaging hit exactly right. It’s now our go-to video for schools and investors.",name:"Bilal Sohail",role:"CEO OF SOFTBANZ",image:image("IMG_6543-2QRg5maFOJtZL1QujTyZ1ZGZg8FkAX.jpeg")},{quote:"We needed accurate 3D models of our FPSO topside for a client proposal. CAD files were a mess and no one could visualize how everything fit together. The models they delivered were insane. Every pipe, valve, and module was to scale. Our engineering team actually used them for clash detection before we even went to the yard. It made the proposal look 10x more professional and we won the bid. They didn’t just model it, they understood how offshore works.",name:"Fabian J",role:"Project Engineer",image:image("IMG_6685-c3UzQsftNBnVHRDd0hNAJ4mXfe97X2.jpeg")}]}/></section>
  <FAQ title="How does the process work?" intro="Still curious about the process? Send us a note and we will walk you through it." items={faq} contactHref="mailto:hello@eliteztudio.com" contactLabel="Contact us"/></>;
}
